### ISSUE TITLE
would it be possible to show us a demo of what this looks like? 

### ISSUE THREAD

**Issue by Solit0123** [wjohnsto/react-headless-yoast#1]
is there a youtube video?

**Comment by wjohnsto** [comment]
This repo is relatively old, and I believe there are newer versions of the Yoast graphql api that make it much easier to use react+yoast+wpgraphql. I would suggest [this resource](https://andrewkepson.com/blog/headless-wordpress/yoast-seo-graphql-headless-wordpress/) for a more up-to-date example.
